# AnyUserNoEscalation()
# [LinuxProbe(), x86Probe()]
# Installs Anaconda to the home directory.

- name: "Install Anaconda Locally"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    user_home: "{{ lookup('env', 'HOME') | default(lookup('env', 'USERPROFILE')) }}"
  tasks:
    - name: "Create Downloads Folder"
      file:
        path: "{{ user_home }}/Downloads/"
        state: directory

    - name: "Download Anaconda"
      get_url:
        url: "https://repo.anaconda.com/archive/Anaconda3-2024.02-1-Linux-x86_64.sh"
        dest: "{{ user_home }}/Downloads/anaconda.sh"

    - name: "Install Anaconda"
      command:
        chdir: "{{ user_home }}/Downloads/"
        cmd: "bash anaconda.sh -b"

    - name: "Remove Anaconda Script"
      file:
        path: "{{ user_home }}/Downloads/anaconda.sh"
        state: absent
