# AnyUserNoEscalation()
# [LinuxProbe(), WhichProbe("fish")]
# Installs the `fisher` plugin for the fish shell and downloads the bass extension for the current user.

- name: "Install latest fish's fisher plugin"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Install fisher and plugins"
      register: aptout
      shell:
        cmd: fish -c "curl -sL https://git.io/fisher | source; fisher install jorgebucaran/fisher; fisher install edc/bass"
    - debug: var=aptout


