# AnyUserNoEscalation()
# [ WhichProbe("conda") ]
# Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.

- name: "Install black"
  hosts: localhost
  connection: local
  become: true # Remove this if AnyUserNoEscalation
  gather_facts: false
  tasks:
    - name: "Install via pip"
      register: aptout
      command:
        cmd: pip install black
    - debug: var=aptout

