# AnyUserNoEscalation()
# [ ExistenceProbe("~/anaconda3") ]
# Peek screen recorder and screenshot with annotations

- name: "Install pypeek"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    conda: ". {{ lookup('env', 'HOME') }}/anaconda3/bin/activate && conda"
  tasks:
    - name: "Create Conda Env if it doesn't exist"
      register: aptout
      shell:
        cmd: "if ! ( {{ conda }} env list | grep -q custom ) ; then {{ conda }} create -y -n custom; fi"
    - debug: var=aptout

    - name: "Install via conda"
      register: aptout
      shell:
        cmd: "{{ conda }} activate custom && python3 -m pip install pypeek"
    - debug: var=aptout


