# AnyUserNoEscalation()
# [ ExistenceProbe("~/anaconda3") ]
# Peek screen recorder and screenshot with annotations

- name: "Install pypeek"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    conda: ". {{ lookup('env', 'HOME') }}/anaconda3/bin/activate && conda"
  tasks:
    - name: "Create Env if it doesn't exist"
      register: aptout
      command:
        shell: "if ! {{ conda }} env list | grep -q custom; conda create -y -n custom; fi"
    - debug: var=aptout

    - name: "Install via pip"
      register: aptout
      command:
        shell: "{{ conda }} activate && pip install pypeek"
    - debug: var=aptout


