# OnlyRoot()
# [ ExistenceProbe("~/anaconda3") ]
# Interactively find and recover deleted or 👉 overwritten 👈 files from your terminal 

- name: "Install RecoverPy"
  hosts: localhost
  connection: local
  become: true # Remove this if AnyUserNoEscalation
  gather_facts: false
  vars:
    conda: "{{ lookup('env', 'HOME') }}/anaconda3/bin/conda"
  tasks:
    - name: "Create Env if it doesn't exist"
      register: aptout
      command:
        shell: "if ! {{ conda }} env list | grep -q custom; conda create -y -n custom; fi"
    - debug: var=aptout

    - name: "Install via pip"
      register: aptout
      command:
        shell: "{{ conda }} activate && pip install recoverpy"
    - debug: var=aptout

