# AnyUserNoEscalation()
# [ ExistenceProbe("~/anaconda3") ]
# trash-cli trashes files recording the original path, deletion date, and permissions. It uses the same trashcan used by KDE, GNOME, and XFCE, but you can invoke it from the command line (and scripts).

- name: "Install trash-cli"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    conda: "{{ lookup('env', 'HOME') }}/anaconda3/bin/conda"
  tasks:
    - name: "Create Env if it doesn't exist"
      register: aptout
      command:
        shell: "if ! {{ conda }} env list | grep -q custom; conda create -y -n custom; fi"
    - debug: var=aptout

    - name: "Install via pip"
      register: aptout
      command:
        shell: "{{ conda }} activate && pip install yt-dlp"
    - debug: var=aptout

