# AnyUserNoEscalation()
# [ ExistenceProbe("~/anaconda3") ]
# trash-cli trashes files recording the original path, deletion date, and permissions. It uses the same trashcan used by KDE, GNOME, and XFCE, but you can invoke it from the command line (and scripts).

- name: "Install trash-cli"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    conda: ". {{ lookup('env', 'HOME') }}/anaconda3/bin/activate && conda"
  tasks:
    - name: "Create Conda Env if it doesn't exist"
      register: aptout
      shell:
        cmd: "if ! ( {{ conda }} env list | grep -q custom ) ; then {{ conda }} create -y -n custom; fi"
    - debug: var=aptout

    - name: "Install via conda"
      register: aptout
      shell:
        cmd: "{{ conda }} activate custom && python3 -m pip install trash-cli"
    - debug: var=aptout

