# AnyUserNoEscalation()
# [ WhichProbe("conda") ]
# A feature-rich command-line audio/video downloader

- name: "Install yt-dlp"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    conda: "{{ lookup('env', 'HOME') }}/anaconda3/bin/conda"
  tasks:
    - name: "Create Env if it doesn't exist"
      register: aptout
      command:
        shell: "if ! {{ conda }} env list | grep -q custom; conda create -y -n custom; fi"
    - debug: var=aptout

    - name: "Install via pip"
      register: aptout
      command:
        shell: "{{ conda }} activate && pip install yt-dlp"
    - debug: var=aptout

