# OnlyRoot()
# [LinuxProbe(), DebianProbe(), NotInDockerProbe(), x86Probe()]
# Downloads latest .deb package for Discord from the website.

- name: "Install Discord"
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: "Install Discord from Website"
      register: aptout2
      apt:
        deb: https://discord.com/api/download?platform=linux&format=deb

    - debug: var=aptout2
