#!/bin/bash

declare -A file_types=(
    ["mp3"]="music"
    ["wav"]="music"
    ["jpg"]="images"
    ["png"]="images"
    ["jpeg"]="images"
    ["gif"]="images"
    ["mp4"]="videos"
    ["mov"]="videos"
    ["mkv"]="videos"
    ["pdf"]="pdf"
    ["zip"]="compressed"
    ["tar"]="compressed"
    ["tar.gz"]="compressed"
    ["deb"]="compressed"
    ["csv"]="docs"
    ["ods"]="docs"
    ["xlsx"]="docs"
    ["txt"]="docs"
    ["docx"]="docs"
    ["doc"]="docs"
    ["py"]="scripts"
    ["bash"]="scripts"
    ["sh"]="scripts"
)

echo -e "\e[36mOrganizing Downloads Folder...\e[0m"
mkdir ~/Down

for file in ~/Downloads/*; do
	if [[ -d "$file" ]]; then
		mv "$file" ~/Down/folders/
	fi

	extension="${file##*.}"
	destination="${file_types[$extension]}"
	if [ -z "$destination" ]; then
		destination="misc"
	fi

	mkdir -p ~/Down/$destination
	mv "$file" ~/Down/$destination
	echo -e "Moved \e[32m${file}\e[0m to \e[36m${destination}\e[0m"
done


