# AnyUserNoEscalation()
# [ WhichProbe("alacritty") ]

- name: "Install alacritty configuration files"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    user_home: "{{ lookup('env', 'HOME') | default(lookup('env', 'USERPROFILE')) }}"
    config_folder: "{{ playbook_dir }}/../../data/config/"
  tasks:

    - name: "Clear existing configuration"
      file:
        path: "{{ user_home }}/.config/alacritty/"
        state: absent

    - name: "Copy configuration"
      copy:
        src: "{{ config_folder }}/alacritty" 
        dest: "{{ user_home }}/.config/"
