# AnyUserNoEscalation()
# [WhichProbe("crontab")]

- name: "Install crontab config"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    user_home: "{{ lookup('env', 'HOME') | default(lookup('env', 'USERPROFILE')) }}"
    scripts_folder: "{{ playbook_dir }}/../../data/scripts/"
  tasks:
    - name: "Install via crontab"
      register: aptout
      shell:
        cmd: "crontab {{ scripts_folder }}/crontab"
    - debug: var=aptout
