# AnyUserEscalation()
# [AptProbe()]
# Installs my i3 config as well as any packages it uses.

- name: "Install i3 configuration files"
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  vars:
    user_home: "{{ lookup('env', 'HOME') | default(lookup('env', 'USERPROFILE')) }}"
    config_folder: "{{ playbook_dir }}/../../data/config/"
  tasks:
    - name: "Install prereqs for my config specifically"
      register: aptout
      apt:
        state: latest
        update_cache: true
        name:
          - git
          - pipx
          - pulseaudio
          - pulsemixer
          - brightnessctl
          - fonts-font-awesome
          - pipx
          - i3blocks
          - picom
          - flameshot
    - debug: var=aptout

    - name: "Download Monocraft font"
      register: aptout 
      get_url:
        url: "https://github.com/IdreesInc/Monocraft/releases/download/v4.0/Monocraft-ttf-otf.zip"
        dest: /tmp/Monocraft.zip
        mode: '0775'
    - debug: var=aptout

    - name: "Uncompress Monocraft font"
      register: aptout
      unarchive:
        src: "/tmp/Monocraft.zip"
        dest: "/tmp/"
        remote_src: yes
    - debug: var=aptout

    - name: "Make Monocraft folder"
      file:
        path: /usr/share/fonts/Monocraft/
        state: directory
        mode: '0755'

    - name: "Install Monocraft font"
      register: aptout
      shell:
        cmd: mv /tmp/other-formats/Monocraft.ttf /usr/share/fonts/Monocraft/
    - debug: var=aptout

    - name: "Reload fonts"
      register: aptout
      shell:
        cmd: fc-cache -f -v
    - debug: var=aptout

    - name: "Install i3-workspace-names-daemon"
      register: aptout
      shell:
        cmd: pipx install i3-workspace-names-daemon
    - debug: var=aptout


    - name: "Clear existing configuration of i3"
      file:
        path: "{{ user_home }}/.config/i3/"
        state: absent

    - name: "Clear existing configuration of i3blocks"
      file:
        path: "{{ user_home }}/.config/i3/"
        state: absent

    - name: "Create dir for i3"
      file:
        path: "{{ user_home }}/.config/i3/"
        state: directory

    - name: "Create dir for i3blocks"
      file:
        path: "{{ user_home }}/.config/i3blocks/"
        state: directory

    - name: "Copy configuration for i3"
      copy:
        src: "{{ config_folder }}/i3/" 
        dest: "{{ user_home }}/.config/i3/"

    - name: "Copy configuration for i3blocks"
      copy:
        src: "{{ config_folder }}/i3blocks/" 
        dest: "{{ user_home }}/.config/i3blocks/"

    - name: "Make i3blocks scripts executable"
      register: aptout
      shell:
        chdir: "{{ user_home }}/.config/i3blocks/"
        cmd: chmod +x *
    - debug: var=aptout

    - name: "Clear existing i3-workspace-names-daemon build"
      file:
        path: "/tmp/i3workspace"
        state: absent

    - name: "Create repo for i3-workspace-names-daemon"
      file:
        path: "/tmp/i3workspace"
        state: directory

    - name: "Install i3-workspace-names-daemon"
      register: aptout
      shell:
        chdir: "/tmp/i3workspace"
        cmd: git clone https://github.com/i3-workspace-names-daemon/i3-workspace-names-daemon

    - name: "Install i3-workspace-names-daemon"
      register: aptout
      shell:
        chdir: "/tmp/i3workspace/i3-workspace-names-daemon"
        cmd: pipx install .
    - debug: var=aptout



