# AnyUserEscalation()
# [AptProbe(), WhichProbe("tmux")]

- name: "Install i3 configuration files"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    user_home: "{{ lookup('env', 'HOME') | default(lookup('env', 'USERPROFILE')) }}"
    config_folder: "{{ playbook_dir }}/../../data/config/"
  tasks:
    - name: "Install prereqs"
      register: aptout
      apt:
        state: latest
        update_cache: true
        name:
          - pulseaudio
          - pulsemixer
          - brightnessctl
    - debug: var=aptout


    - name: "Clear existing configuration"
      file:
        path: "{{ user_home }}/.config/i3/"
        state: absent

    - name: "Create dir for data"
      file:
        path: "{{ user_home }}/.config/i3/"
        state: directory

    - name: "Copy configuration"
      copy:
        src: "{{ config_folder }}/i3/" 
        dest: "{{ user_home }}/.config/i3/"

