# [ LinuxProbe(), WhichProbe("docker"), NotRootProbe() ]
# Adds the current user to the docker group so that no `sudo` is needed to run docker. 

- name: "Install Docker so no sudo is needed"
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: "Create docker group"
      group:
        name: "docker"
        state: present

    - name: "Add current user to docker group"
      user:
        name: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
        groups: docker
        append: yes
