# [LinuxProbe(), DebianProbe(), RootProbe()]
# Installs nmap, binwalk, chkrootkit, testdisk, and steghide.

- name: "Hacking Tools for Debian"
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: "Install Packages"
      register: aptout
      apt:
        state: latest
        name: 
          - nmap
          - binwalk
          - chkrootkit
          - testdisk
          - steghide

    - debug: var=aptout
