# OnlyRoot()
# [LinuxProbe(), x86Probe() ]
# Installs the `nvim` AppImage. This may not work out of the box on systems without FUSE.

- name: "Install nvim"
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: "Download nvim AppImage"
      register: aptout3
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
        dest: /usr/bin/nvim
        mode: '0775'
      
    - debug: var=aptout3

