# [ DebianProbe() ]

- name: Install Rust
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install Build Packages for Rust
      register: aptout
      apt:
        state: latest
        name:
          - curl
    - debug: var=aptout


    - name: Install Rust
      register: aptout2
      shell:
        cmd: curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
    - debug: var=aptout2
