# AnyUserEscalation() 
# [LinuxProbe(), NotInDockerProbe(), WhichProbe("docker"), ExistenceProbe("~/box/bin/") ]
# Installs ollama locally, then installs the ollama-docker command.

- name: "Install Ollama Webui"
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  vars:
    user_home: "{{ lookup('env', 'HOME') | default(lookup('env', 'USERPROFILE')) }}"
    docker_folder: "{{ playbook_dir }}/../../data/docker/"
  tasks:
    - name: "Install ollama command"
      register: aptout
      shell:
        cmd: "curl -fsSL https://ollama.com/install.sh | sh"
    - debug: var=aptout

    - name: "Install ollama script"
      register: aptout
      copy:
        src: "{{ docker_folder }}/ollama-docker" 
        dest: "{{ user_home }}/box/bin/"
    - debug: var=aptout

    - name: "Fix permissions"
      shell:
        cmd: "chmod +x {{ user_home }}/box/bin/ollama-docker"
    - debug: var=aptout



