# AnyUserNoEscalation() 
# [LinuxProbe(), NotInDockerProbe(), WhichProbe("bash"), ExistenceProbe("~/box/bin/") ]
# Install snippets

- name: "Install Snippets"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    user_home: "{{ lookup('env', 'HOME') | default(lookup('env', 'USERPROFILE')) }}"
    docker_folder: "{{ playbook_dir }}/../../data/docker/"
  tasks:
    - name: "Install snippets script"
      register: aptout
      copy:
        src: "{{ docker_folder }}/snippets-docker" 
        dest: "{{ user_home }}/box/bin/"
    - debug: var=aptout

    - name: "Fix permissions"
      shell:
        cmd: "chmod +x {{ user_home }}/box/bin/snippets-docker"
    - debug: var=aptout



