#!/bin/bash

if [[ "$1" == "export" ]]
then
	if ! [[ -e ~/.local/share/snippet-box ]]
	then
		echo "No data found."
		exit 1
	fi

	cp ~/.local/share/snippet-box/db.sqlite3 .
	tar -czf snippets_data.tar.gz db.sqlite3
	rm db.sqlite3

	echo "Export success"

	exit 0
fi


if [[ "$1" == "import" ]] && [[ $# -eq 2 ]]
then
	folder=$(mktemp -d)
	cp "$2" "$folder"
	cd "$folder"
	if tar -xf "${2}"
	then
		sudo mv db.sqlite3  ~/.local/share/snippet-box/db.sqlite3
	else
		echo "Unable to extract."
		exit 1
	fi

	echo "Import success. Make sure to restart docker container for changes to take effect."

	exit 0
elif [[ "$1" == "import" ]]
then
	echo "Missing file."
	exit 1
fi

SNIPPETS=~/box/snippet-box/

if ! [[ -e $SNIPPETS ]] || (docker images | grep -v "snippet-box")
then
	docker rmi snippet-box
    mkdir -p ~/box/
	git clone https://github.com/pawelmalak/snippet-box $SNIPPETS
	cd $SNIPPETS
	docker build -t snippet-box .
fi

if which docker > /dev/null 2>&1
then
	docker run --rm -it -p 5000:5000 -v ~/.local/share/snippet-box:/app/data snippet-box
else
	echo "Docker is not installed."
fi
