# [LinuxProbe(), x86Probe()]

- name: "Install bat"
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: "Install Bat"
      register: aptout2
      apt:
        deb: https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-musl_0.24.0_amd64.deb

    - debug: var=aptout2
